#+TITLE: My Emacs Config
#+AUTHOR: Shimmy Xu
#+TODO: DISABLED(t) | ENABLED(d)

This is my humble collection of Emacs config, modeled after
[[https://github.com/admiralakber/simplemacs][simplemacs]], documented
in an hopefully understandable manner. I went from using multiple
=.org= files back to a single one because =org-mode= is fantastic and
my config is not too complicated for a single file to handle (yet).

| Module            | Function                     |
|-------------------+------------------------------|
| [[Packages]]      | Package management.          |
| [[Aesthetics]]    | UI and theme.                |
| [[Enhancements]]  | Plug-and-play enhancements.  |
| [[Plugins]]       | Larger scale packages.       |
| [[Mode Specific]] | Settings specific to a mode. |

* Packages
Manage my package settings.

** Package Repositories
Initialize Emacs Package Manager and add repositories.
#+BEGIN_SRC emacs-lisp
  (package-initialize)
  (require 'package)
  (let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                      (not (gnutls-available-p))))
         (url (concat (if no-ssl "http" "https") "://melpa.org/packages/")))
        (add-to-list 'package-archives (cons "melpa" url) t))
  (when (< emacs-major-version 24)
    ;; For important compatibility libraries like cl-lib
    (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
#+END_SRC

** Setup =use-package=
Bootstrap =use-package= so that package requirements can be handled in separate
sections.
#+BEGIN_SRC emacs-lisp
  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))
#+END_SRC

* Aesthetics
Mostly aesthetics and quality of life changes.

** 80 Character Limit
Set =fill-column= to 80 characters.
#+BEGIN_SRC emacs-lisp
  (setq-default fill-column 80)
#+END_SRC

Highlight portions of line over 80 characters in =prog-mode=.
#+BEGIN_SRC emacs-lisp
  (require 'whitespace)
  (setq whitespace-line-column 80)
  (setq whitespace-style '(face empty tabs lines-tail trailing))
  (add-hook 'prog-mode-hook 'whitespace-mode)
#+END_SRC

** Color Themes
Install =base16-theme= and enable gruvbox dark pale.
#+BEGIN_SRC emacs-lisp
    (use-package base16-theme
      :ensure t
      :config
      (load-theme 'base16-gruvbox-dark-pale t))
#+END_SRC

** Customize Settings in Separate File
Save customized settings in a separate file than =init.el=. Create the customization file if none found.
#+BEGIN_SRC emacs-lisp
  (setq custom-file (expand-file-name "custom.el" user-emacs-directory))
  (unless (file-exists-p custom-file)
    (write-region "" "" custom-file))
  (load custom-file)
#+END_SRC

** Fcitx
Install fcitx support.
#+BEGIN_SRC emacs-lisp
  (use-package fcitx
    :ensure t
    :init
    (fcitx-aggressive-setup)
    (setq fcitx-use-dbus t))
#+END_SRC

*** Daemon Support
If using Emacs daemon with =systemd=, remember to add to the
=.service= file:

#+BEGIN_SRC sh
  Environment="LC_CTYPE=zh_CN.UTF-8" "XMODIFIERS=@im=fcitx"
#+END_SRC

It would also help to change the default command for =emacs= into:
#+BEGIN_SRC sh
  emacsclient -c -a emacs
#+END_SRC

** Font Settings
*** Default Fonts
Specify both Latin font and CJK font.
#+BEGIN_SRC emacs-lisp
  (defvar user/latin-font "Iosevka Term"
    "Default font for Latin characters.")

  (defvar user/cjk-font "Noto Sans CJK SC"
    "Default font for CJK characters.")

  (defvar user/font-size 17
    "Default font size in px.")
#+END_SRC

*** CJK Font Fallback Logic
Fallback logic for CJK fonts, ensures correct font and size gets used for CJK.

**** CJK Font Scaling.
Ensure CJK fonts scales correctly to twice the width of half-width characters.
#+BEGIN_SRC emacs-lisp
  (defvar user/cjk-font-scale
    '((16 . 1.0)
      (17 . 1.1)
      (18 . 1.0))
    "Scaling factor to use for cjk font of given size.")

  ;; Specify scaling factor for CJK font.
  (setq face-font-rescale-alist
        (list (cons user/cjk-font
                    (cdr (assoc user/font-size user/cjk-font-scale)))))
#+END_SRC

**** CJK Enabled Fontset
To ensure fontset gets correctly configured, I simply created one from
scratch. This is because =emacsclient= seems to have a different dynamic when
creating =startup-fontset= and no other method guarantees consistent behavior
between =emacs= and =emacsclient=.

#+BEGIN_SRC emacs-lisp
  (defvar user/standard-fontset
    (create-fontset-from-fontset-spec standard-fontset-spec)
    "User fontset with cjk font fallback.")

  ;; Enable font customization for charset symbols.
  ;; This charset contains puncuation marks, emoji, and etc..
  (setq use-default-font-for-symbols nil)

  (defun user/set-font ()
    "Set Latin and CJK font for user/standard-fontset."
    ;; Latin font.
    (set-fontset-font user/standard-fontset 'latin
                      (font-spec :family user/latin-font :size user/font-size)
                      nil 'prepend)
    ;; CJK font.
    (dolist (charset '(kana han cjk-misc bopomofo))
      (set-fontset-font user/standard-fontset charset
                        (font-spec :family user/cjk-font)
                        nil 'prepend))
    ;; Special settings for certain CJK puncuation marks.
    (dolist (charset '((#x2018 . #x2019)    ;; CJK single quotes
                       (#x201c . #x201d)))  ;; CJK double quotes
      (set-fontset-font user/standard-fontset charset
                        (font-spec :family user/cjk-font)
                        nil 'prepend)))

  ;; Ensure user/standard-fontset gets used for new frames.
  (add-to-list 'default-frame-alist (cons 'font user/standard-fontset))
  (add-to-list 'initial-frame-alist (cons 'font user/standard-fontset))

  ;; Apply changes.
  (user/set-font)
  ;; For emacsclient.
  (add-hook 'before-make-frame-hook #'user/set-font)
#+END_SRC

** Line Highlighting
Enable line highlighting.
#+BEGIN_SRC emacs-lisp
  (global-hl-line-mode t)
#+END_SRC

** Line Numbering
Use =display-line-numbers= instead of =linum=.
Enable relative line numbering, and set minimum width to 3.
#+BEGIN_SRC emacs-lisp
  (setq-default display-line-numbers-type (quote relative))
  (setq-default display-line-numbers-width 3)
  (global-display-line-numbers-mode)
#+END_SRC

** Line Wrapping
Enable line wrapping by default.
#+BEGIN_SRC emacs-lisp
  (global-visual-line-mode t)
#+end_SRC

** No Tabs
Use spaces for indenting.
#+BEGIN_SRC emacs-lisp
  (setq-default indent-tabs-mode nil)
#+END_SRC

** Parenthesis Highlighting
Highlight matching parenthesis.
#+BEGIN_SRC emacs-lisp
  (show-paren-mode t)
#+END_SRC

** Rainbow Delimiters
=rainbow-delimiters= is a "rainbow parentheses"-like mode which highlights delimiters such as parentheses, brackets or braces according to their depth.

Install =rainbow-delimiters= and enable it for =prog-mode=.
#+BEGIN_SRC emacs-lisp
  (use-package rainbow-delimiters
    :ensure t
    :init (add-hook 'prog-mode-hook #'rainbow-delimiters-mode))
#+END_SRC

** Remove Trailing Whitespace
Remove trailing whitespace upon saving.
#+BEGIN_SRC emacs-lisp
  (add-hook 'before-save-hook 'delete-trailing-whitespace)
#+END_SRC

** Save Backups Elsewhere
Save =*~= backups in =$(pwd)/.bak=.
#+BEGIN_SRC emacs-lisp
  (setq backup-directory-alist
        '(("." . ".bak"))
        )
#+END_SRC

** Show Column Number
#+BEGIN_SRC emacs-lisp
  (setq column-number-mode t)
#+END_SRC

** UI Settings
*** *bars
Hide menu, scrollbar and toolbars.
#+BEGIN_SRC emacs-lisp
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
  (tool-bar-mode -1)
#+END_SRC

**** New Frame Scrollbar
Remove scrollbar for any new frames as well, useful for =emacsclient=.
#+BEGIN_SRC emacs-lisp
  (defun user/disable-scroll-bars (frame)
    (modify-frame-parameters frame
                             '((vertical-scroll-bars . nil)
                               (horizontal-scroll-bars . nil))))
  (add-hook 'after-make-frame-functions 'user/disable-scroll-bars)
#+END_SRC

*** Half screen fix
Fills up gap in the border when tiling Emacs to half-screen.
#+BEGIN_SRC emacs-lisp
  (setq frame-resize-pixelwise t)
#+END_SRC

** Zoom In
Use mouse wheel to adjust zoom level.
#+BEGIN_SRC emacs-lisp
  (global-set-key [C-mouse-4] 'text-scale-increase)
  (global-set-key [C-mouse-5] 'text-scale-decrease)
#+END_SRC

* Enhancements
Packages providing enhancements to Emacs interface. Mostly simple
plug-and-play packages.

** Dashboard
An extensible Emacs startup screen showing you what’s most important.

*** Installation
Change default startup screen with =dashboard=.
Customize =initial-buffer-choice= to affect new frames created by =emacsclient=.
Also refresh dashboard to ensure customizations take effect.
#+BEGIN_SRC emacs-lisp
  (use-package dashboard
    :ensure t
    :config
    (dashboard-setup-startup-hook)
    (setq initial-buffer-choice (lambda()
                                  (dashboard-refresh-buffer)
                                  (get-buffer "*dashboard*"))))
#+END_SRC

*** Customize Banner and Logo
Customize banner and logo.
#+BEGIN_SRC emacs-lisp
  (defvar user/dashboard-banner-logo-titles
    '("42"
      "9 MORE SEASONS UNTIL I GET THAT DIPPING SZECHUAN SAUCE!"
      "Execute order 66."
      "Greetings from Emacs!"
      "Project-iM@CS"
      "Weak emperors mean strong viceroys."
      "Wubba Lubba Dub-Dub!"))
  (setq dashboard-banner-logo-title
        (elt user/dashboard-banner-logo-titles
             (random (length user/dashboard-banner-logo-titles))))
  (setq dashboard-startup-banner
        (expand-file-name "static/sxs.png" user-emacs-directory))
#+END_SRC

*** Customize Widgets
**** =dashboard-insert-configs=
Create widget to display important config files. Use ~c~ to jump to this section.
#+BEGIN_SRC emacs-lisp
  (defvar user/config-file-list
    (mapcar (lambda (arg) (expand-file-name arg user-emacs-directory))
            '("README.org"
              "init.el")))

  (defun user/dashboard-insert-configs (list-size)
    "Add a list of config files."
    (when (dashboard-insert-recentf-list
           "Config Files:"
           (dashboard-subseq user/config-file-list 0 (length user/config-file-list)))
      (dashboard-insert-shortcut "c" "Config Files:")))

  (add-to-list 'dashboard-item-generators '(configs . user/dashboard-insert-configs))
#+END_SRC

**** =dashboard-insert-init-time=
Display initialization time.
#+BEGIN_SRC emacs-lisp
  (defun user/dashboard-insert-init-time (list-size)
     "Displays Emacs init time."
     (insert (format "[Started Emacs in %s.]" (emacs-init-time))))

  (add-to-list 'dashboard-item-generators '(init-time . user/dashboard-insert-init-time))
#+END_SRC

**** Apply All Widgets
Set items to display:
#+BEGIN_SRC emacs-lisp
  (setq dashboard-items '((recents  . 5)
                          (bookmarks . 5)
                          (projects . 8)
  ;                        (agenda . 5)
  ;                        (registers . 5)
                          (configs)
                          (init-time)))
#+END_SRC

** HTML Export
Convert buffer text and decorations to HTML by =htmlize-buffer= so
that people can see what I see.
#+BEGIN_SRC emacs-lisp
  (use-package htmlize
    :ensure t)
#+END_SRC

** Keyfreq
Records command frequency. I am planning on adjusting my keyboard
layout with this information.
#+BEGIN_SRC emacs-lisp
    (use-package keyfreq
      :ensure t
      :init
      (keyfreq-mode 1)
      (keyfreq-autosave-mode 1))
#+END_SRC

** Magit
Install =magit= and bind =magit-status= to ~C-c g~.
#+BEGIN_SRC emacs-lisp
  (use-package magit
    :ensure t
    :init
    (global-set-key (kbd "C-c g") 'magit-status))
#+END_SRC

** Projectile
Projectile is a project interaction library for Emacs. Its goal is to
provide a nice set of features operating on a project level without
introducing external dependencies(when feasible).

*** Installation
Install =projectile=.
#+BEGIN_SRC emacs-lisp
  (use-package projectile
    :ensure t
    :init
    (projectile-global-mode))
#+END_SRC

*** Enable =helm= support
Since I use =helm=, I need to install additional support.
#+BEGIN_SRC emacs-lisp
  (use-package helm-projectile
    :ensure t
    :init
    (setq projectile-completion-system 'helm)
    (helm-projectile-on))
#+END_SRC

* Plugins
Larger scale packages that either requires more configuration, or
fundamentally changes how Emacs behave. Because these package
configurations is a lot more complex and may be spread out, any
subtree that depends on packages in this section will have a tag to
mark the dependency.

** Helm
Stolen from Admiral Akber's config.

*** Info
Helm is incredible, it really supercharges emacs. It's a framework for
incremental searching / completion / narrowing down options. Sounds
simple, and it is in application, and it's so worth it.

Web: [[https://emacs-helm.github.io/helm/]]
Git: [[https://github.com/emacs-helm/helm]]
#+BEGIN_SRC emacs-lisp
  (use-package helm
    :ensure t
    :init (helm-mode t))
  (require 'helm-config)
#+END_SRC

*** Visual customization
I want helm to automatically resize and appear in the current buffer
only.
#+BEGIN_SRC emacs-lisp
  (setq helm-autoresize-mode 1)
  (setq helm-split-window-in-side-p t)
#+END_SRC

*** Fuzzy matching
Fuzzy matching works most of the time, it does seem to have the issue
of only matching forward i.e. "machine snow" will not match with "snow
machine".

It does make it a lot easier to search through Emacs functions though
as you only need to remember one part of the function name.
#+BEGIN_SRC emacs-lisp
  ;; Enable Fuzzy Matching
  (setq helm-recentf-fuzzy-match       t
        helm-buffers-fuzzy-matching    t
        helm-recentf-fuzzy-match       t
        helm-buffers-fuzzy-matching    t
        helm-locate-fuzzy-match        t
        helm-apropos-fuzzy-match       t
        helm-lisp-fuzzy-completion     t
        helm-candidate-number-limit    250)
#+END_SRC

*** Keybindings
Above defaults overides such as =M-x= these are custom bindings.

**** Self help
The Emacs culture is to have great documentation with your functions,
all searchable via =apropos=. Helm provides a nice interface to this,
use it often.
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-h a") 'helm-apropos)
  (global-set-key (kbd "C-h i") 'helm-info-emacs)
#+END_SRC

**** Buffers and files
Buffers and files are an obvious case where helm is very useful.
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x b")   'helm-mini)
  (global-set-key (kbd "C-x C-b") 'helm-buffers-list)
  (global-set-key (kbd "M-x")     'helm-M-x)
  (global-set-key (kbd "C-x C-f") 'helm-find-files)
  (global-set-key (kbd "C-x C-r") 'helm-recentf)
  (global-set-key (kbd "C-x r l") 'helm-filtered-bookmarks)
#+END_SRC

**** Advanced editing
Kill ring memory, grepping, etc, all gorgeous with helm.
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "M-y")     'helm-show-kill-ring)
  (global-set-key (kbd "C-x c g") 'helm-do-grep)
  (global-set-key (kbd "C-x c o") 'helm-occur)
#+END_SRC

**** The overloaded tab key
The good ol' =TAB= key is used for a lot, in this case I want to make
sure that when used in helm that it completes in helm, not attempting
to insert a snippet or something.
#+BEGIN_SRC emacs-lisp
  (define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action)
#+END_SRC

Also, the following makes sure that tab works when running in terminal
mode:
#+BEGIN_SRC emacs-lisp
  (define-key helm-map (kbd "C-i") 'helm-execute-persistent-action)
#+END_SRC

This requires fixing the select other actions which IIRC is set to
~C-i~ by default.
#+BEGIN_SRC emacs-lisp
  (define-key helm-map (kbd "C-z") 'helm-select-action)
#+END_SRC

** Company
Auto completion of everything with nice backends.

*** Installation
Install =company= and enable it globally.
#+BEGIN_SRC emacs-lisp
  (use-package company
    :ensure t
    :init (global-company-mode))
#+END_SRC

*** Adjust Delay
Set delay for auto-completion. 0 would be too extreme and wastes CPU clocks apparently.
#+BEGIN_SRC emacs-lisp
  (setq company-idle-delay 0.01)
  (setq company-minimum-prefix-length 2)
#+END_SRC

*** =yasnippet= Conflict
Pressing tab with company mode conflicts with =yasnippets=, this is
the only fix that I found that makes everything work as expected.
#+BEGIN_SRC emacs-lisp
  (defun user/check-expansion()
    (save-excursion
      (if (looking-at "\\_>") t
        (backward-char 1)
        (if (looking-at "\\.") t
          (backward-char 1)
          (if (looking-at "->") t nil)))))

  (defun user/do-yas-expand()
    (let ((yas-fallback-behavior 'return-nil))
      (yas-expand)))

  (defun user/tab-indent-or-complete()
    (interactive)
    (if (minibufferp)
        (minibuffer-complete)
      (if (or (not yas-minor-mode)
              (null (user/do-yas-expand)))
          (if (user/check-expansion)
              (company-complete-common)
            (indent-for-tab-command)))))

  (global-set-key (kbd "TAB") 'user/tab-indent-or-complete)
#+END_SRC

*** Tooltip Documentation
Install dependency =pos-tip=.
#+BEGIN_SRC emacs-lisp
  (use-package pos-tip
    :ensure t)
  (require 'pos-tip)
#+END_SRC

Install =company-quickhelp= and set delay, FG/BG colors, max lines.
#+BEGIN_SRC emacs-lisp
  (use-package company-quickhelp
    :ensure t
    :init
    (company-quickhelp-mode t)
    (setq company-quickhelp-delay 0.01)
    (setq company-quickhelp-color-background "#262626")
    (setq company-quickhelp-color-foreground "#ebdbb2")
    (setq company-quickhelp-max-lines 20)
    (setq company-quickhelp-use-propertized-text t))
#+END_SRC

*** Backend Configurations
**** =company-math=
Install =company-math= and add it to =company-backends=.

Enable unicode symbol backend globally.
#+BEGIN_SRC emacs-lisp
   (use-package company-math
     :ensure t
     :init (add-to-list 'company-backends
                        '(company-math-symbols-unicode)))
#+END_SRC

Enable math symbol backend only in =TeX-mode=.
#+BEGIN_SRC emacs-lisp
  (defun company-math-init ()
    (setq-local company-backends
                (append '((company-math-symbols-latex))
                        company-backends)))

  (add-hook 'TeX-mode-hook 'company-math-init)
#+END_SRC

**** =company-auctex=
Install =company-auctex= and add it to =company-backends=. This is for =acutex= macro completion.
Adding backends is handled by =company-auctex-init=.
#+BEGIN_SRC emacs-lisp
  (use-package company-auctex
    :ensure t
    :init (company-auctex-init))
#+END_SRC

**** =company-yasnippet=
Add =company-yasnippet= backend for =yasnippet= key completion.
#+BEGIN_SRC emacs-lisp
  (defun user/enable-yas-for-backend (backend)
    "Add yasnippet support for specified BACKEND."
    (if (and (listp backend) (member 'company-yasnippet backend))
        backend
      (append (if (consp backend) backend (list backend))
              '(:with company-yasnippet))))
  ;; Enable for all backends.
  (setq company-backends (mapcar #'user/enable-yas-for-backend company-backends))
#+END_SRC

** Flycheck
Flycheck is a modern on-the-fly syntax checking extension for GNU
Emacs, intended as replacement for the older Flymake extension which
is part of GNU Emacs.

*** Installation
Install =flycheck=.
#+BEGIN_SRC emacs-lisp
  (use-package flycheck
    :ensure t
    :init (global-flycheck-mode))
#+END_SRC

*** Set C++ Standard Library
Use =c++14= as the C++ standard.
#+BEGIN_SRC emacs-lisp
  (add-hook 'c++-mode-hook
            (lambda () (progn
                         (setq flycheck-cppcheck-standards '("c++14"))
                         (setq flycheck-clang-language-standard "c++14")
                         (setq flycheck-gcc-language-standard "c++14"))))
#+END_SRC

*** Set Google C++ Syntax Checker
**** Install =flycheck-google-cpplint=
Add Google C++ Style checker for =flycheck= (Now deprecated, using local copy).
On Arch Linux, if using AUR package =cpplint=, need to modify command
in =flycheck-google-cpplint.el= to use =cpplint= instead of
=cppling.py=.
#+BEGIN_SRC emacs-lisp
  (use-package flycheck-google-cpplint
    :load-path "local/flycheck-google-cpplint/"
    :config
    (eval-after-load 'flycheck
      '(progn
         (require 'flycheck-google-cpplint)
         ;; Add Google C++ Style checker.
         ;; In default, syntax checked by Clang and Cppcheck.
         ;; Use Google Checker after errors are cleared
         (flycheck-add-next-checker 'c/c++-cppcheck
                                    '(error . c/c++-googlelint)))))
#+END_SRC

**** Set Checker Parameters
Set various parameters for the checker.
#+BEGIN_SRC emacs-lisp
  (custom-set-variables
   '(flycheck-googlelint-verbose "5")
   '(flycheck-googlelint-filter "-legal/copyright")
   '(flycheck-googlelint-linelength "80"))
#+END_SRC

*** Set Clang Analyzer
**** Install =flycheck-clang-analyzer=
#+BEGIN_SRC emacs-lisp
  (use-package flycheck-clang-analyzer
    :ensure t
    :init
    (with-eval-after-load 'flycheck
      (require 'flycheck-clang-analyzer)
      (flycheck-clang-analyzer-setup)))
#+END_SRC

** Yasnippet
YASnippet is a template system for Emacs. It allows you to type an
abbreviation and automatically expand it into function templates.

*** Installation
Install =yasnippet=. Load =yasnippet= when =yas-minor-mode= is called
and add the hook for =yas-minor-mode= for programming modes. Reload
the snippets on start up.
#+BEGIN_SRC emacs-lisp
  (require 'cl)
  (use-package yasnippet
    :ensure t
    :commands (yas-minor-mode)
    :init (yas-global-mode)
    :config (yas-reload-all))
#+END_SRC

*** Install =yasnippet-snippets=
=yasnippet-snippets= is a collection of snippets for many langulages.
#+BEGIN_SRC emacs-lisp
  (use-package yasnippet-snippets
    :ensure t)
#+END_SRC

* Mode Specific
Settings specific to a mode or defines a new mode that often
specializes Emacs for a certain programming language.

** Auctex
=auctex= is an extensible package for writing and formatting TEX files
in GNU Emacs.

*** Installation
Need to use =defer= as =auctex.el= does not actually provide =auctex= feature.
#+BEGIN_SRC emacs-lisp
  (use-package auctex
    :defer t
    :ensure t)
#+END_SRC

*** Automatic Parsing
Enable =auctex= to automatically parse buffer information.
#+BEGIN_SRC emacs-lisp
  (setq TeX-parse-self t)
  (setq TeX-auto-save t)
  (setq TeX-save-query nil)
#+END_SRC

*** Master File Detection
Let =auctex= figure out the master file for TeX document spread over many files.
#+BEGIN_SRC emacs-lisp
  (setq-default TeX-master nil)
#+END_SRC

*** Spell Checking
Spell checking with =flyspell=.
#+BEGIN_SRC emacs-lisp
  (add-hook 'LaTeX-mode-hook 'flyspell-mode)
#+END_SRC

*** Enable =reftex=
Turn on RefTeX Mode for all LaTeX files. This enables you to jump via table of contents.
The key to invoke this is ~C-c =~.
#+BEGIN_SRC emacs-lisp
  (add-hook 'LaTeX-mode-hook 'turn-on-reftex)   ; with AUCTeX LaTeX mode
#+END_SRC

*** Enable =LaTeX-math-mode=
Enable LaTeX Math mode. This allows macro insertion following ~`~.
Not exactly useful since we already have =company=.
#+BEGIN_SRC emacs-lisp
  (add-hook 'LaTeX-mode-hook 'LaTeX-math-mode)
#+END_SRC

**** Auto-complete Sub/Superscripts
Insert braces after ~_~ or ~^~.
#+BEGIN_SRC emacs-lisp
  (setq TeX-electric-sub-and-superscript t)
#+END_SRC

** C/C++-mode
*** DISABLED Default Indention
Set default indention level to 4 and style to "linux"(do not indent braces).
#+BEGIN_SRC emacs-lisp
  (setq-default c-default-style "linux"
                c-basic-offset 4)
#+END_SRC

*** Google Style
Google's C/C++ style for c-mode.
**** Installation
#+BEGIN_SRC emacs-lisp
  (use-package google-c-style
    :ensure t
    :init
    (add-hook 'c-mode-common-hook 'google-set-c-style)
    (add-hook 'c-mode-common-hook 'google-make-newline-indent))
#+END_SRC

*** Treat =.h= as C++
Identify =.h= files as C++ files instead of C. To enable =c++-mode=
manually, type =M-x c\+\+-mode=.
#+BEGIN_SRC emacs-lisp
  (add-to-list 'auto-mode-alist '("\\.h\\'" . c++-mode))
#+END_SRC

*** Clang-format
**** Installation
Install and set hot keys for formatting.
#+BEGIN_SRC emacs-lisp
  (use-package clang-format
    :ensure t
    :init
    (global-set-key (kbd "C-c i") 'clang-format-region)
    (global-set-key (kbd "C-c u") 'clang-format-buffer))
#+END_SRC

**** Set code style
Use Google's C++ style.
#+BEGIN_SRC emacs-lisp
  (custom-set-variables '(clang-format-style "Google"))
#+END_SRC

** ESS
Emacs Speaks Statistics (ESS) is an add-on package for emacs text editors such as GNU Emacs and XEmacs. It is designed to support editing of scripts and interaction with various statistical analysis programs such as R, S-Plus, SAS, Stata and OpenBUGS/JAGS.
#+BEGIN_SRC emacs-lisp
  (use-package ess
    :ensure t)
#+END_SRC

** Org-mode
=org-mode= specific settings.

*** Formatting
**** Set Link Format
Do not collapse the links.
#+BEGIN_SRC emacs-lisp
  (org-toggle-link-display)
#+END_SRC

**** Subtree Indention
Do not change text indention when promoting/demoting subtrees.
#+BEGIN_SRC emacs-lisp
  (setq org-adapt-indentation nil)
#+END_SRC

**** Truncate Lines by Default
Automatically enable truncated lines when starting =org-mode=.
#+BEGIN_SRC emacs-lisp
  (setq-default org-startup-truncated t)
#+END_SRC

**** DISABLED Turn Off =auto-fill=
Disable =auto-fill-mode= when in =org-mode=.
#+BEGIN_SRC emacs-lisp
  (add-hook 'org-mode-hook 'turn-off-auto-fill)
#+END_SRC

**** Display Inline Images
Display inline images for =org-babel= execution results.
#+BEGIN_SRC emacs-lisp
(add-hook 'org-babel-after-execute-hook 'org-display-inline-images)
(add-hook 'org-mode-hook 'org-display-inline-images)
#+END_SRC

**** Protect Folded Regions
Don't allow editing of folded regions
#+BEGIN_SRC emacs-lisp
  (setq org-catch-invisible-edits 'error)
#+END_SRC

*** Enable spell checking
Spell checking with =flyspell-mode=. Would need to install dictionary lib like =aspell= in base system.
#+BEGIN_SRC emacs-lisp
  (add-hook 'org-mode-hook 'flyspell-mode)
#+END_SRC

*** Enable Code Evaluation
Enable evaluation of various languages in org-mode.
#+BEGIN_SRC emacs-lisp
  (defvar user/org-babel-enabled-languages
    '(emacs-lisp
      python
      R
      org)
    "Extra languages user can execute in org-babel code blocks.")

  (org-babel-do-load-languages
   'org-babel-load-languages
   (mapcar
    (lambda (arg) (cons arg t))
    user/org-babel-enabled-languages))
#+END_SRC

There is no need to confirm execution for these languages.
#+BEGIN_SRC emacs-lisp
  (setq org-confirm-babel-evaluate
        (lambda (lang body)
          (not (member lang
                       (mapcar (lambda (arg) (symbol-name arg))
                               user/org-babel-enabled-languages)))))
#+END_SRC

*** Exporter Backends
**** HTML
Do not export validation link.
#+BEGIN_SRC emacs-lisp
  (setq org-html-validation-link nil)
#+END_SRC

**** Markdown (Blackfriday)
An Org exporter backend that exports Org to Hugo-compatible Markdown
(Blackfriday) and generates the front-matter (in TOML or YAML format).

***** Installation
Enable =ox-hugo= as an option for exporting.
#+BEGIN_SRC emacs-lisp
  (use-package ox-hugo
    :ensure t
    :init (with-eval-after-load 'ox (require 'ox-hugo)))
#+END_SRC

***** Export Key Bindings
Wrap key bindings in =<kbd>=.
#+BEGIN_SRC emacs-lisp
  (setq org-hugo-use-code-for-kbd t)
#+END_SRC

** Rust-mode
A compilation of settings for programming in rust.

*** Rust-mode
Install =rust-mode=, use =rust-fmt= to format the code upon saving,
and automatically enable =rust-mode= for =*.rs= files.
#+BEGIN_SRC emacs-lisp
  (use-package rust-mode
    :ensure t
    :init
    (setq rust-format-on-save t)
    (add-to-list 'auto-mode-alist '("\\.rs\\'" . rust-mode))
  )
#+END_SRC

*** Flycheck Support
Better flycheck support via =flycheck-rust=.
#+BEGIN_SRC emacs-lisp
  (use-package flycheck-rust
    :ensure t
    :init
    (with-eval-after-load 'rust-mode
      (add-hook 'flycheck-mode-hook #'flycheck-rust-setup)))
#+END_SRC
